sources = ['squfof64.cc',
           'squfof128.cc',
           'squfof.cc',
	   '../libfactor-stats.a',
           '../../liboptarith/liboptarithxx.a',
           '/usr/local/lib/libgmp.a']

Program(target='squfof',
        source=sources,
        CCFLAGS=['-std=c++11', '-O3', '-DNDEBUG'],
        CPPPATH=['../..'],
        LIBS=['m', 'rt'])


